#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source_dir="${LIBMSEED_SOURCE_DIR:-${script_dir}/libmseed}"
allowlist_file="${LIBMSEED_EXPORT_ALLOWLIST:-${script_dir}/libmseed.exports}"
wasm_output="${script_dir}/libmseed.wasm"

if ! command -v emcc >/dev/null 2>&1; then
  echo "error: emcc was not found in PATH" >&2
  exit 1
fi

if ! command -v make >/dev/null 2>&1; then
  echo "error: make was not found in PATH" >&2
  exit 1
fi

if [[ ! -f "${source_dir}/libmseed.h" ]]; then
  echo "error: upstream libmseed source not found at ${source_dir}" >&2
  exit 1
fi

if [[ ! -f "${source_dir}/Makefile" ]]; then
  echo "error: upstream libmseed Makefile not found at ${source_dir}" >&2
  exit 1
fi

if [[ ! -f "${allowlist_file}" ]]; then
  echo "error: export allowlist not found at ${allowlist_file}" >&2
  exit 1
fi

if ! make_output="$(make --no-print-directory -s -C "${source_dir}" print-LIB_SRCS)"; then
  echo "error: failed to read LIB_SRCS from ${source_dir}/Makefile" >&2
  exit 1
fi
if [[ "${make_output}" != LIB_SRCS=* ]]; then
  echo "error: unexpected print-LIB_SRCS output: ${make_output}" >&2
  exit 1
fi
read -r -a sources <<< "${make_output#LIB_SRCS=}"
if (( ${#sources[@]} == 0 )); then
  echo "error: LIB_SRCS is empty in ${source_dir}/Makefile" >&2
  exit 1
fi

source_paths=()
for source in "${sources[@]}"; do
  source_path="${source_dir}/${source}"
  if [[ ! -f "${source_path}" ]]; then
    echo "error: required libmseed source is missing: ${source_path}" >&2
    exit 1
  fi
  source_paths+=("${source_path}")
done

symbols=(malloc free)
declare -A seen_symbols=([malloc]=1 [free]=1)

while IFS= read -r line || [[ -n "${line}" ]]; do
  symbol="${line%%#*}"
  symbol="${symbol#"${symbol%%[![:space:]]*}"}"
  symbol="${symbol%"${symbol##*[![:space:]]}"}"
  [[ -z "${symbol}" ]] && continue

  if [[ ! "${symbol}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "error: invalid export name in ${allowlist_file}: ${symbol}" >&2
    exit 1
  fi
  if [[ -n "${seen_symbols[${symbol}]:-}" ]]; then
    echo "error: duplicate export name in ${allowlist_file}: ${symbol}" >&2
    exit 1
  fi
  if ! grep -Eq "(^|[^A-Za-z0-9_])${symbol}[[:space:]]*\(" "${source_dir}/libmseed.h"; then
    echo "error: ${symbol} is not declared by upstream libmseed.h" >&2
    exit 1
  fi

  seen_symbols["${symbol}"]=1
  symbols+=("${symbol}")
done < "${allowlist_file}"

if (( ${#symbols[@]} == 2 )); then
  echo "error: export allowlist contains no libmseed functions" >&2
  exit 1
fi

exported_functions="["
separator=""
for symbol in "${symbols[@]}"; do
  exported_functions+="${separator}\"_${symbol}\""
  separator=","
done
exported_functions+="]"

temporary_dir="$(mktemp -d "${script_dir}/.libmseed-wasm.XXXXXX")"
trap 'rm -rf -- "${temporary_dir}"' EXIT
temporary_wasm="${temporary_dir}/libmseed.wasm"
temporary_exports="${temporary_dir}/libmseed.exports"

emcc "${source_paths[@]}" \
  -I"${source_dir}" \
  -O3 \
  -g0 \
  -o "${temporary_wasm}" \
  -s WASM=1 \
  -s ERROR_ON_UNDEFINED_SYMBOLS=1 \
  -s EXPORTED_FUNCTIONS="${exported_functions}" \
  -Wl,--no-entry

{
  echo "# Code generated by build_libmseed_wasm.sh; DO NOT EDIT."
  printf '%s\n' "${symbols[@]}"
} > "${temporary_exports}"

mv -- "${temporary_wasm}" "${wasm_output}"

echo "built ${wasm_output}"
